### ISSUE TITLE
Re: OSX, zdb needs largeblock support

### ISSUE THREAD

**Issue by lundman** [zfsonlinux/zfs#3468]
Sorry to pass the buck a bit, but maybe those who know more than me can solve it faster.. :)

https://github.com/openzfsonosx/zfs/issues/322

To summarize the issue discovered on OSX which exists upstream on Linux and Illumos:

```
Create pool with zpool without large_block support:

ftp01.dw:~$ uname -a
SunOS ftp01 5.11 oi_151a6 i86pc i386 i86pc Solaris
root@ftp01:~# mkfile 100M /var/tmp/filepool.bin
root@ftp01:~# zpool create BOOM /var/tmp/filepool.bin
root@ftp01:~# mkdir /BOOM/helloworld
root@ftp01:~# zpool export BOOM
root@ftp01:~# scp /var/tmp/filepool.bin ssh01.newer:/var/tmp/
Import pool on system with large_block support, but do not upgrade

root@ssh01:/export/home/lundman# uname -a
SunOS ssh01 5.11 omnios-170cea2 i86pc i386 i86pc
root@ssh01:/export/home/lundman# zpool import -d /var/tmp/ BOOM
root@ssh01:/export/home/lundman# zdb -ddddddd BOOM
[snip]
Indirect blocks:
               0 L0 0:ba00:200 0:120ba00:200 200L/200P F=1 B=7/7

                segment [0000000000000000, 0000000000000200) size   512

large_blocks feature refcount mismatch: expected 0 != actual -2748781167608
```

**Comment by lundman** [comment]
Brian was working on this during zfsday, but now it seems maybe it came from IllumOS? Should we make a ticket there?

Seems to affect pools created before largeblock support.

**Comment by behlendorf** [comment]
Matt managed to push large block support over the finish line.  We've merged it back in to ZoL so you should be able to pull those changes pretty easily.

**Comment by lundman** [comment]
Yep, we have those changes and came across this problem. Then we confirmed the problem happens on ZOL as well.  But I guess I should take it straight to @ahrens  :)

**Comment by behlendorf** [comment]
I should have read the issue you linked too.  :)  Yup definitely something to fix!

**Comment by ahrens** [comment]
Looks like a bug specific to ZoL/OSX; not present in illumos, where i and last_nonzero are declared as signed numbers.  I would guess that when porting to Linux, you changed this code (because you don't use C99, for reasons I still can't understand).

**Comment by behlendorf** [comment]
@lundman it doesn't look like this code was modified from illumos.  I don't see why they wouldn't have the same issue but I haven't investigated carefully yet.  Perhaps it just went overlooked there.

@ahrens we can, and do, use C99 for the user space bits like zdb.  There was no code change here.  As for not using C99 in the kernel take it up with the rest of the Linux kernel community.  They have their own guidelines https://www.kernel.org/doc/Documentation/CodingStyle about this.  We can either  a) keep the code C89 and build with the default kernel build options, or b) build C99 and override the default kernel opens.  I happened to pick a) early on but we could switch to b).

**Comment by maci0** [comment]
Since ZoL will never be Integrated into the mainline kernel why not switch to b).....
Should make porting upstream ZFS patches more straightforward and further reduce code differences

**Comment by chrisrd** [comment]
I think @maci0 makes a good point. Having done a fair number of patch ports, making patches easier to apply and confirm would be a good thing. If the Gods of Licensing ever smile upon us and allow ZoL to somehow go mainline the global ecstasy will drown out the inconvenience of having to revert to C88 (if indeed that's still required if/when this magical event occurs).

**Comment by lundman** [comment]
It is somewhat amusing that ZOL changes all the `zfsvfs` into `zsb`, then when I merge downstream, I change all `zsb` to `zfsvfs`. (and a bunch more) If only there was a solution for that :)

I hope brian and ahrens also check the original issue ticket in osx so that the actual problem gets some attention :)

**Comment by behlendorf** [comment]
@lundman this isn't on the top of my list but it is something I plan to look in too!

Not to get off track but let me digress for a minute.  Way way way back when I started the port for Linux and absolutely nothing at all worked it made considerably more sense to change the relatively small number of C99'ism for two reason.

1) Changing / modifying the license was being discussed (w/Sun) and it wasn't totally hopeless.
2) Making the kernel happy reduced the potential for subtle annoying bugs.

Today the situation is somewhat different and I agree it makes sense to adopt C99.  There's still the outside possibility it will cause an issue since the kernel makes some assumptions about how things are compiled.  I'm sure we'd notice any major issues quickly but something subtle, I don't know what, could be overlooked.

Keep in mind it wasn't until fairly recently that you could build the kernel with a compiler __other__ than gcc.   And it wasn't that long ago when Linux distributions would ship the __exact version__ of gcc used to build the kernel solely for the purpose of allowing 3rd party developers to build out of tree modules.  Those days are behind us now, but there were valid reason to be cautious.

That said, if someone wants to put together some patches to update the build system that would be a good start.  I think @ryao may already have done this.  And if someone wants to go the extra mile and propose patches to undo the C99->C89 changes that'd be even better.

> I change all zsb to zfsvfs

The best way to address this would be refactor the VFS code so that it can properly accommodate different platforms.  It just so happens that illumos, FreeBSD, and OSx VFSs all work in basicallty the same way so the changes needed I suspect were minimal.  Linux however is a very different beast so the changes go much deeper.  I'm sure things can be refactored but it's a big chunk of work.  And it's a chunk of work which should probably happen.

**Comment by don-brady** [comment]
I have a fix for the issue: `large_blocks feature refcount mismatch: expected 0 != actual -2748781167608`

**Comment by lundman** [comment]
Thanks everyone, I merged ZOL today to get the latest patches.

We still need the `(int)` part in the for loop, unsure why our compiler defaults to unsigned and yours signed;

```
    for (i = 0; (int) i <= last_nonzero; i++) {
```

Also one more comment, the new merge would panic immediately at:

```
 kernel[0]: spl-taskq.c taskq_dispatch_ent 1374 : ASSERTION(!(tq->tq_flags & TASKQ_DYNAMIC)) failed
kernel[0]: kernel memory allocator: buffer modified after being freed
kernel[0]: modification occurred at offset 0x358 (0xdeadbeefdeadbeef replaced by 0xffffff80b017e690)
kernel[0]: buffer=0xffffff80b017dba8  bufctl=0xffffff80afe87750  cache: zio_cache
```

The ASSERT is triggered in `taskq_dispatch_ent` because `TASKQ_DYNAMIC` is set on. ZOL sets this flag in spa.c 
https://github.com/zfsonlinux/zfs/blob/master/module/zfs/spa.c#L847
and yet, uses `taskq_dispatch_ent`
https://github.com/zfsonlinux/zfs/blob/master/module/zfs/spa.c#L957

Compared to IllumOS:
https://github.com/illumos/illumos-gate/blob/master/usr/src/uts/common/fs/zfs/spa.c#L851

Which means in IllumOS taskq (and we ported theirs directly) the ASSERT is triggered:

https://github.com/illumos/illumos-gate/blob/master/usr/src/uts/common/os/taskq.c#L1298

but worse, it gets freed here (when _ent should not be freed!)
https://github.com/illumos/illumos-gate/blob/master/usr/src/uts/common/os/taskq.c#L1607

Now, easy to fix for us and we have moved on, but I don't know the details of ZOL's taskq, if you are indeed trying to free something that can't be freed or not.

**Comment by behlendorf** [comment]
@lundman glad you picked up the latest changes.  I'm not sure about the `(int)` issue either.

Thanks for the warning about TASKQ_DYNAMIC.  This is a recent change, aa9af22cdf8d16c197974c3a478d2053b3bed498, applied to ZoL.  Our taskq implementation was recently updated to safely support the TASKQ_DYNAMIC flag even for entries dispatched with `taskq_dispatch_ent()`.  So we took the opportunity to apply that flag broadly to cut down of the number of idle threads on the system.  Obviously you'll want to drop that flag if this isn't something supported by the illumos taskqs.

**Comment by lundman** [comment]
Ah, thanks for explaining it to me. The only issue was mixing DYNAMIC with the taskq_dispatch_ent() style, since apparently that is not valid.  Currently we changed our flags back to 0 in zio/spa as it is the only place these two conditions meet, but having looked over the taskq sources, I could also change the source to let DYNAMIC be used with ent() style, there seems to be no obvious reason for the two styles to be mutually exclusive.
