### ISSUE TITLE
internal error: out of memory on gentoo/zfs-0.6.5.3-r1

### ISSUE THREAD

**Issue by janlam7** [zfsonlinux/zfs#4112]
After upgrading from gentoo/zfs-0.6.5.3 to gentoo/zfs-0.6.5.3-r1 one of my systems fails to boot.
During /etc/init.d/zfs-import 'internal error: out of memory' appears, and the initramfs fails to find the real root which is on a zfs dataset.
I can enter an 'ash' shell at that point, and 'zfs list' only shows 2 of the datasets, so the pool seems to be somewhat imported.
Booting again into the 0.6.5.3 version seems to work flawlessly.

Some information:
Kernel is gentoo-sources 4.1.12
Pool was created in july 2013 and has seen all versions between then and now, including some time running against the master branch.
Machine has 32G ECC ram, so I'm hoping it is not a real memory problem ;-)

Where to go from here ?

**Comment by behlendorf** [comment]
@janlam7 thanks for filing this.  Let me just make sure @ryao who maintains the Gentoo package is aware of this since it sounds like it's distribution specific.

**Comment by janlam7** [comment]
@behlendorf, @ryao I just installed the gentoo/zfs-9999 ebuild and dependencies, and the machine will boot without problems. I'll keep it running on this version for a while.

**Comment by ryao** [comment]
@janlam7 It sounds like the userland tools were upgraded, but the modules in the initramfs were not. Are you sure that both were upgraded at the same time?

**Comment by janlam7** [comment]
@ryao, I just reinstalled zfs, zfs-kmod and spl, all 0.6.5.3-r1; and recreated the initramfs.
I diffed the contents of the intramfs regarding zfs and the modules with the root filesystem, and they all seem to match. Booting failed with the same error. I'm not sure what else to compare.

I tried spl-0.6.5.3-r1 together with zfs 0.6.5.3 and zfs-kmod 0.6.5.3; that boots normally.
I made an ebuild for zfs and zfs-kmod 0.6.5.3 with only 0001-ClusterHQ-Proposed-API-extensions.patch applied -> same error after booting.
Changing the ebuild for apply only 0002-libzfs-handle-EDOM-errors.patch makes it boot succesful again.

Can the 0001-ClusterHQ-Proposed-API-extensions.patch safely be split into smaller parts ?

**Comment by janlam7** [comment]
So, to be sure there is no mismatch with the versions in the initramfs I copied my zfs-root and /usr to an ext4 partition, put the 0.6.5.3-r1 versions on it, removed the zfs stuff from the runlevels and booted from it. No 'out of memory errors' occur, but the listing of datasets is still not complete. Notice the missing '/data' after zfs list, but the succesfully mounted /data later on, after mounting manually.

mediacenter / # zpool import pool4
mediacenter / # zfs list
NAME        USED  AVAIL  REFER  MOUNTPOINT
pool4      1.64T   137G   149K  /
pool4/lxc  27.8G   137G  8.26G  /lxc
pool4/mnt   202K   137G   202K  /mnt
mediacenter / # zfs mount pool4/data
mediacenter / # df
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/sda7        8125880   5727840   2381656  71% /
tmpfs            3262904       884   3262020   1% /run
dev                10240         0     10240   0% /dev
shm             16314504         0  16314504   0% /dev/shm
cgroup_root        10240         0     10240   0% /sys/fs/cgroup
none            16314504     10532  16303972   1% /tmp
pool4/lxc      152646016   8664064 143981952   6% /lxc
pool4/data     760598528 616616576 143981952  82% /data
mediacenter / # zfs list
NAME        USED  AVAIL  REFER  MOUNTPOINT
pool4      1.64T   137G   149K  /
pool4/lxc  27.8G   137G  8.26G  /lxc
pool4/mnt   202K   137G   202K  /mnt 

Any suggestions on what to try next ?

**Comment by AndCycle** [comment]
@ryao 
here is a screenshot for reference as I tried 0.6.5.3-r1,
http://imgur.com/0Q4y5gF

you can see it only list first few zfs,
that zpool actually contain much more than that
```
zroot                                      360G  69.9G   136K  legacy
zroot/prod                                 360G  69.9G   144K  legacy
zroot/prod/lz4                             360G  69.9G   136K  legacy
zroot/prod/lz4/default                     360G  69.9G   136K  legacy
zroot/prod/lz4/default/mysql              18.0G  69.9G  9.86G  legacy
zroot/prod/lz4/default/postgresql          199G  69.9G   123G  legacy
zroot/prod/lz4/default/root               38.8G  69.9G  32.5G  legacy
zroot/prod/lz4/default/var                 104G  69.9G  51.4G  legacy
```
then I rollback the entire system because this is a prod server,

**Comment by janlam7** [comment]
The out of memory error is triggered by the the following command from the initramfs:
zfs get type -o value -H pool/system/zfs06531 (in my case)

**Comment by ryao** [comment]
@behlendorf Could you assign this and other Gentoo specific issues to me to me so that it is a little easier to manage?

@janlam7 This seems to work fine in what should be -r2. I will be pushing that out later today.

If this should ever happen in the future, please join the #zfsonlinux channel on freenode and ping me daily until I get it fixed. Anything that breaks boot should be my top priority. The time of year and family commitments made keeping track of this harder to keep track of this than it should have been.

**Comment by janlam7** [comment]
@ryao I just installed the -r2 version, updated the initramfs and as far as I can tell, my issues did not change. I'll try with a dedicated ext4 root partition on wednesday. 
spl is still on the -r1 version, is that intended ?

**Comment by janlam7** [comment]
Tried -r2 with a root on ext4. zfs list gives the same output as with -r1. Back to 0.6.5.3 for me.
How can I help debug this ?

**Comment by ryao** [comment]
@janlam7 Would you contact me in #zfsonlinux on the freenode IRC network? It will be faster than using the issue tracker.

**Comment by janlam7** [comment]
@ryao On another machine I just upgraded I get the same error-text, but during another command.

quad3400 ~ # zfs list -t snapshot | head -n2 
NAME                        USED  AVAIL  REFER  MOUNTPOINT
pool3@20160109                 0      -   128K  -
quad3400 ~ # zfs list -H -o used pool3@20160109 
internal error: out of memory
quad3400 ~ # modinfo zfs | head -n 2
filename:       /lib/modules/4.1.12-gentoo/extra/zfs/zfs.ko
version:        0.6.5.3-r2-gentoo

**Comment by ScottESanDiego** [comment]
I get this with Gentoo on my 4.4.0 system using -r2.  Looks like most anything that wants to touch snapshots is broken:

intrepid ~ # zfs list -H -o used tank/GENTOO/mail@backupsnapshot_latest
internal error: out of memory

intrepid ~ # zfs destroy tank/GENTOO/mail@backupsnapshot_latest
internal error: out of memory

:-(

**Comment by ilovezfs** [comment]
@ScottESanDiego Yes, ryao is already hard at work fixing this: https://github.com/zfsonlinux/zfs/issues/4204

If you need a workaround immediately, you can build the spl-9999/zfs-9999 ebuilds, or use the .zfs snapdir to interact with the snapshots.

**Comment by ryao** [comment]
I have pushed fixes for this to the gentoo-next branch in my github repository:

https://github.com/ryao/zfs/tree/gentoo-next

There is one more reported issue that I want to address and I am still testing it, but I am hopeful that I can get things updated later today.

**Comment by ilovezfs** [comment]
@ryao Yup, things seem to back to normal now on the O3X server running https://github.com/ryao/zfs/tree/gentoo-next

Thanks!

**Comment by janlam7** [comment]
@ryao Nice, seems to be working again on the one machine I tried the gentoo-next branch on.

**Comment by alexanderhaensch** [comment]
@ryao getting properties works now. 
Destroying snapshots is still not possible.

**Comment by ilovezfs** [comment]
@alexanderhaensch You sure you actually are using the fixed code? See below.
```
openzfs ~ # zpool create gn `pwd`/tmp.bin
openzfs ~ # zfs create -p gn/abc/def
openzfs ~ # zfs snap -r gn@A
openzfs ~ # zfs snap -r gn/abc@B
openzfs ~ # zfs snap gn/abc/def@C
openzfs ~ # zfs list -r -t snap gn
NAME           USED  AVAIL  REFER  MOUNTPOINT
gn@A              0      -    19K  -
gn/abc@A          0      -    19K  -
gn/abc@B          0      -    19K  -
gn/abc/def@A      0      -    19K  -
gn/abc/def@B      0      -    19K  -
gn/abc/def@C      0      -    19K  -
openzfs ~ # zfs destroy gn/abc@B
openzfs ~ # zfs destroy gn/abc@A
openzfs ~ # zfs list -r -t snap gn
NAME           USED  AVAIL  REFER  MOUNTPOINT
gn@A              0      -    19K  -
gn/abc/def@A      0      -    19K  -
gn/abc/def@B      0      -    19K  -
gn/abc/def@C      0      -    19K  -
openzfs ~ # zfs destroy gn/abc/def@C
openzfs ~ # zfs destroy -r gn/abc/def
openzfs ~ # zfs list -r -t snap gn
NAME   USED  AVAIL  REFER  MOUNTPOINT
gn@A      0      -    19K  -
openzfs ~ # zfs destroy gn@A
openzfs ~ # zfs list -r -t snap gn
no datasets available
openzfs ~ #
```

**Comment by alexanderhaensch** [comment]
@ilovezfs Yes you are right. I was missing the system reboot. My setup is now: gentoo 0.6.5.3-r2 + the 6 patches from @ryao s gentoo-next on top of that. Seems to work. Thanks!

**Comment by ilovezfs** [comment]
@alexanderhaensch Cool, glad you got it working. Same setup here basically, except that I mirrored https://github.com/ryao/zfs/tree/gentoo-next at https://github.com/ilovezfs/zfsonlinux-zfs and then modified the 0.6.5.3-r2 ebuilds to use that and skip the patching (similar to how the 9999 versions do). The results should be identical to what you did.

**Comment by ryao** [comment]
I pushed out 0.6.5.3-r3 today. The delays were caused by my attempts to verify that I had fixed every reported regression in -r2 so there would not need to be an -r4.

**Comment by alexanderhaensch** [comment]
@ryao I guess 0.6.4.3-r3 is pretty much upstream 0.6.5.4 + API patches?

**Comment by janlam7** [comment]
@ryao The 2nd machine I had problems with now works perfectly. The original machine I filed this report for still gives the out of memory error on boot. zfs list now returns 'no datasets available' instead of returning an incomplete list like berofe. I'll move the rootfs from zfs to an ext4 partition to rule out initramfs issues again.

**Comment by ilovezfs** [comment]
@alexanderhaensch Not quite, but not too far from the truth:
https://gist.github.com/ilovezfs/bd6dac157669907a9d4f

**Comment by janlam7** [comment]
@ryao Booting from an ext4 root and trying to import afterwards now gives an out of memory during importing.

mediacenter ~ # zpool import pool4 -f -R /mnt/gentoo   
internal error: out of memory
mediacenter ~ # zpool import pool4 -R /mnt/gentoo 
cannot import 'pool4': a pool with that name already exists
use the form 'zpool import <pool | id> <newpool>' to give it a new name
mediacenter ~ # zfs list
no datasets available

**Comment by janlam7** [comment]
@ryao Just tried importing without mounting. Gives no 'out of memory' but no datasets too. Listing the snapshots gives the complete list afaik.

mediacenter ~ # zpool import pool4 -N -f -R /mnt/gentoo 
mediacenter ~ # zfs list
no datasets available
mediacenter ~ # zfs list -t snapshot
NAME                                 USED  AVAIL  REFER  MOUNTPOINT
pool4@20160116                          0      -   149K  -
....

**Comment by ilovezfs** [comment]
@janlam7 You're most likely not actually running 0.6.5.3-r3:
https://gist.github.com/ilovezfs/31ae91380261e53f33c8

```
openzfs ~ # dmesg |grep 0.6.5.3
[   16.813327] SPL: Loaded module v0.6.5.3-r1-gentoo
[   16.939488] ZFS: Loaded module v0.6.5.3-r3-gentoo, ZFS pool version 5000, ZFS filesystem version 5
openzfs ~ # cat /sys/module/{spl,zfs}/version
0.6.5.3-r1-gentoo
0.6.5.3-r3-gentoo
openzfs ~ # modinfo spl zfs|grep 0.6.5.3
version:        0.6.5.3-r1-gentoo
version:        0.6.5.3-r3-gentoo
openzfs ~ # ls -l /lib/modules/4.1-sabayon/extra/spl/spl.ko /lib/modules/4.1-sabayon/extra/zfs/zfs.ko /sbin/zfs /usr/lib/libzfs.so /usr/lib/libnvpair.so 
-rw-r--r-- 1 root root  123464 Jan 17 14:04 /lib/modules/4.1-sabayon/extra/spl/spl.ko
-rw-r--r-- 1 root root 1747448 Jan 17 14:16 /lib/modules/4.1-sabayon/extra/zfs/zfs.ko
-rwxr-xr-x 1 root root  109608 Jan 17 14:23 /sbin/zfs
-rwxr-xr-x 1 root root     529 Jan 17 14:23 /usr/lib/libnvpair.so
-rwxr-xr-x 1 root root     526 Jan 17 14:23 /usr/lib/libzfs.so
openzfs ~ # 
```

**Comment by janlam7** [comment]
@lovezfs I was I wasn't but I think I am.

mediacenter ~ # dmesg | grep Loaded
[    1.582427] SPL: Loaded module v0.6.5.3-r1-gentoo
[    1.630271] ZFS: Loaded module v0.6.5.3-r3-gentoo, ZFS pool version 5000, ZFS filesystem version 5
[    2.227004] ivtv0: Loaded v4l-cx2341x-enc.fw firmware (376836 bytes)
mediacenter ~ # cat /sys/module/{spl,zfs}/version
0.6.5.3-r1-gentoo
0.6.5.3-r3-gentoo

**Comment by ilovezfs** [comment]
And you've rebooted? Also can you get the modification times of your userland commands and libraries vs. those of the kernel modules?

**Comment by janlam7** [comment]
Yes rebooted. Emerged spl, zfs and zfs_kmod to be sure, and rebooted again. Below are the filedates.

mediacenter lib # ls -alt /sbin/{zfs,zpool}
-rwxr-xr-x 1 root root 103208 Jan 17 14:19 /sbin/zfs
-rwxr-xr-x 1 root root 122312 Jan 17 14:19 /sbin/zpool
mediacenter lib # ls -alt /lib/libzfs*
lrwxrwxrwx 1 root root     15 Jan 17 14:19 /lib/libzfs.so.2 -> libzfs.so.2.0.0
lrwxrwxrwx 1 root root     20 Jan 17 14:19 /lib/libzfs_core.so.1 -> libzfs_core.so.1.0.0
-rwxr-xr-x 1 root root 275872 Jan 17 14:19 /lib/libzfs.so.2.0.0
-rwxr-xr-x 1 root root  18464 Jan 17 14:19 /lib/libzfs_core.so.1.0.0
mediacenter lib # ls -alt /lib/libzpool*
lrwxrwxrwx 1 root root      17 Jan 17 14:19 /lib/libzpool.so.2 -> libzpool.so.2.0.0
-rwxr-xr-x 1 root root 1261608 Jan 17 14:19 /lib/libzpool.so.2.0.0
mediacenter lib # ls -alt /usr/lib/libzfs*
-rwxr-xr-x 1 root root 526 Jan 17 14:19 /usr/lib/libzfs.so
-rwxr-xr-x 1 root root 531 Jan 17 14:19 /usr/lib/libzfs_core.so
mediacenter lib # ls -alt /usr/lib/libzpool*
-rwxr-xr-x 1 root root 528 Jan 17 14:19 /usr/lib/libzpool.so
mediacenter lib # ls -alt /lib/modules/4.1.12-gentoo/extra/zfs/
total 1852
drwxr-xr-x  2 root root    4096 Jan 17 14:17 .
-rw-r--r--  1 root root 1886664 Jan 17 14:16 zfs.ko
drwxr-xr-x 10 root root    4096 Jan  8 09:59 ..
mediacenter lib # ls -alt /lib/modules/4.1.12-gentoo/extra/spl
total 136
drwxr-xr-x  2 root root   4096 Jan 17 14:10 .
-rw-r--r--  1 root root 128872 Jan 17 14:10 spl.ko
drwxr-xr-x 10 root root   4096 Jan  8 09:59 ..

**Comment by ilovezfs** [comment]
And how about
```
# which -a zfs zpool | xargs ldd
```

**Comment by janlam7** [comment]
mediacenter / # which -a zfs zpool | xargs ldd
/sbin/zfs:
	linux-vdso.so.1 (0x00007ffc85bd9000)
	libnvpair.so.1 => /lib64/libnvpair.so.1 (0x00007f387b9c7000)
	libuutil.so.1 => /lib64/libuutil.so.1 (0x00007f387b7af000)
	libzpool.so.2 => /lib64/libzpool.so.2 (0x00007f387b30f000)
	libzfs.so.2 => /lib64/libzfs.so.2 (0x00007f387b0c7000)
	libzfs_core.so.1 => /lib64/libzfs_core.so.1 (0x00007f387aebf000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f387ac9f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f387a907000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f387a6ff000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f387a4f7000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f387a2df000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f387bbdf000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f3879fd7000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f3879d8f000)
/sbin/zpool:
	linux-vdso.so.1 (0x00007ffeed5d1000)
	libnvpair.so.1 => /lib64/libnvpair.so.1 (0x00007fdca8c3f000)
	libuutil.so.1 => /lib64/libuutil.so.1 (0x00007fdca8a27000)
	libzpool.so.2 => /lib64/libzpool.so.2 (0x00007fdca8587000)
	libzfs.so.2 => /lib64/libzfs.so.2 (0x00007fdca833f000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007fdca80f7000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007fdca7eef000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fdca7ccf000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fdca7937000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fdca772f000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fdca7517000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdca8e57000)
	libzfs_core.so.1 => /lib64/libzfs_core.so.1 (0x00007fdca730f000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fdca7007000)

/lib is a symlink to /lib64 btw.

**Comment by ilovezfs** [comment]
try running this
```
#!/bin/bash
store=/root/tmpfoo.bin
rm -f /root/tmpfoo.bin
fallocate -l 256m ${store}
zpool create tmpfoo ${store}
echo test1 ...
zfs list | grep tmpfoo
echo test2 ...
zfs list tmpfoo | grep tmpfoo
echo test3 ....
zfs create -p tmpfoo/A/B
zfs list | grep tmpfoo
echo test4 ...
zfs list tmpfoo | grep tmpfoo
echo test5 ...
zfs snap -r tmpfoo@s0
zfs list | grep tmpfoo
echo test6 ...
zfs snap -r tmpfoo/A@s1
zfs list -t snap | grep tmpfoo
echo test7 ...
zfs snap tmpfoo/A/B@s2
zfs list tmpfoo | grep tmpfoo
echo test8 ...
zfs list -t filesystem | grep tmpfoo
echo test9 ...
zfs list -t filesystem tmpfoo | grep tmpfoo
echo test10 ...
zfs list -t all -r tmpfoo | grep tmpfoo
zpool export tmpfoo
rm ${store}
```

**Comment by janlam7** [comment]
That gives no errors and seems to work as expected.

mediacenter ~ # sh ilovezfs 
test1 ...
tmpfoo    49K   208M    19K  /tmpfoo
test2 ...
tmpfoo    49K   208M    19K  /tmpfoo
test3 ....
tmpfoo       104K   208M    19K  /tmpfoo
tmpfoo/A      38K   208M    19K  /tmpfoo/A
tmpfoo/A/B    19K   208M    19K  /tmpfoo/A/B
test4 ...
tmpfoo   104K   208M    19K  /tmpfoo
test5 ...
tmpfoo       105K   208M    19K  /tmpfoo
tmpfoo/A      38K   208M    19K  /tmpfoo/A
tmpfoo/A/B    19K   208M    19K  /tmpfoo/A/B
test6 ...
tmpfoo@s0          0      -    19K  -
tmpfoo/A@s0        0      -    19K  -
tmpfoo/A@s1        0      -    19K  -
tmpfoo/A/B@s0      0      -    19K  -
tmpfoo/A/B@s1      0      -    19K  -
test7 ...
tmpfoo   106K   208M    19K  /tmpfoo
test8 ...
tmpfoo       106K   208M    19K  /tmpfoo
tmpfoo/A      38K   208M    19K  /tmpfoo/A
tmpfoo/A/B    19K   208M    19K  /tmpfoo/A/B
test9 ...
tmpfoo   106K   208M    19K  /tmpfoo
test10 ...
tmpfoo          106K   208M    19K  /tmpfoo
tmpfoo@s0          0      -    19K  -
tmpfoo/A         38K   208M    19K  /tmpfoo/A
tmpfoo/A@s0        0      -    19K  -
tmpfoo/A@s1        0      -    19K  -
tmpfoo/A/B       19K   208M    19K  /tmpfoo/A/B
tmpfoo/A/B@s0      0      -    19K  -
tmpfoo/A/B@s1      0      -    19K  -
tmpfoo/A/B@s2      0      -    19K  -

Hm, does that indicate I have some bitrot happening in my pool which scrub does not pick up ?
I don't mind recreating the pool and restoring from a backup, but I can imagine I'm not the only one with this issue.

**Comment by AndCycle** [comment]
@janlam7 no, I think I have the same symptoms like yours, 
but I don't have machine to spare for debugging so it's up to you if you wanna get involve into this.

**Comment by ilovezfs** [comment]
@janlam7 Good, that's identical output to what I get here.

I don't think it's going to have anything to do with bitrot, but it does make it sound pool specific. We need to figure out what's different with that pool.

zpool status pool4
zpool list | grep pool4
zfs list | grep pool4
zfs list pool4
zfs list -r pool4
zfs list -r -t filesystem pool4
zfs list -r -t all pool4
zfs mount | grep pool4
mount | grep pool4
zfs get all | grep pool4
zpool get all | grep pool4

Probably should use a gist or pastebin for the output.

**Comment by ryao** [comment]
@alexanderhaensch 0.6.5.3-r2 had most of what became 0.6.5.4 backported. 0.6.5.3-r3 is just API fixes on top of that. 0.6.5.4 will be in tree soon. I am going through a backlog of bug reports.

@janlam7 It sounds like you did not update your initramfs, such that an older module is loaded. What does `cat /sys/module/zfs/version` output? Also, could you contact me in #zfsonlinux on freenode so that we can debug this interactively?

**Comment by janlam7** [comment]
@ilovezfs The output you requested is at https://gist.github.com/janlam7/7820694e91afdb444b43

**Comment by ryao** [comment]
@janlam7 Would you by any chance have installed ZFS outside of the package manager at some point in time, such that you would have binaries in `/usr/local/{bin,lib}`?

**Comment by ilovezfs** [comment]
@ryao The <code>which -a</code> above would have caught that, I think.

@janlam7 The bug appears to be gone. Quoting from your gist above:

>mediacenter ~ # zfs list | grep pool4
pool4                      1019G   783G   149K  /
...

So it is listing the datasets, and not giving "no datasets available." Do you agree that the bug is gone?

**Comment by janlam7** [comment]
@ilovezfs 
The results are from the working zfs version I have.
I shall redo them tonight with the non working version, after importing without mounting.
The bug is not gone.

**Comment by ryao** [comment]
@ilovezfs Not for /usr/local/lib being used by things in /sbin.

**Comment by janlam7** [comment]
@ilovezfs I added a gist for the -r3 zfs version results on https://gist.github.com/janlam7/aebd847d6f4fa7236933

@ryao /usr/local/lib and /usr/local/bin are empty

**Comment by janlam7** [comment]
Not sure if it means anything but I enabled zfs_dbgmsg and the last lines look like this:

1453156065   looking up system in obj4
1453156065   looking up home in obj4
1453156065   looking up home in obj4
1453156065   looking up home in obj4
1453156065   looking up home in obj4
1453156065   looking up $ORIGIN in obj4

system and home I can relate to, but not to $ORIGIN.

**Comment by ilovezfs** [comment]
@janlam7 You should probably do as ryao suggested and go to #zfsonlinux on IRC to debug this with him interactively.

Are the working and non-working machine both running the same kernel? Also what's the output of 

```
# equery uses spl zfs-kmod zfs
```

One interesting but probably unrelated discrepancy between the two gists is
```
pool4  cachefile                   -                           default
```
vs.
```
pool4  cachefile                   none                        local
```
I wonder what accounts for that.

Only other thing I can think of is to emerge --unmerge spl zfs-kmod zfs and then scour the system for any file names associated with zfs using find or updatedb+locate.

**Comment by janlam7** [comment]
@ryao Something interesting happened. I destroyed a dataset which I didn't use. It had canmount=off.
Makes no difference for zfs-0.6.5.3, but in zfs-0.6.5.3-r3 zfs list now returned 1 dataset (still an incomplete list)
emerge zfs 0.6.5.3 again ....
add a dataset
emerge zfs-0.6.5.3-r3 : the new dataset also shows up in zfs list
emerge zfs 0.6.5.3 again ....
I did set recordsize=4K on the new dataset
emerge zfs-0.6.5.3-r3 : zfs list shows 'no datasets available' again

If i boot with zfs-kmod-0.6.5.3-r3 and zfs-0.6.5.3 I notice a lot of datasets having canmount=off,  inherited from the root pool. 
man zfs says 'This property is not inherited.'

**Comment by janlam7** [comment]
@ryao just provided a working patch, nice.

**Comment by ryao** [comment]
Gentoo has been updated with that patch and several other fixes. We should be able to close this.

**Comment by janlam7** [comment]
Maybe @AndCycle can check if the new version fixes it. I re-installed my system since then and cannot reproduce it anymore.

**Comment by AndCycle** [comment]
@janlam7 just test the updated ver, 

=sys-fs/zfs-0.6.5.4-r2
=sys-fs/zfs-kmod-0.6.5.4-r1
=sys-kernel/spl-0.6.5.4-r1

work as expected now, I think this issue can be closed.

**Comment by janlam7** [comment]
Ok, nice.

**Comment by AndCycle** [comment]
ok, I am too optimistic, there is something changed that make zrep think there is no info for sync that I setup previously, need another ticket for this one
