### ISSUE TITLE
docs: must `zfs allow refreservation` to create a zvol

### ISSUE THREAD

**Issue by homerlinux** [zfsonlinux/zfs#8531]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Mint
Distribution Version	| 19.1
Linux Kernel	|  4.15.0-46-generic
Architecture	|  x86_64
ZFS Version	|  0.7.5-1ubuntu16.4
SPL Version	|  0.7.5-1ubuntu1

### Describe the problem you're observing
granting permissions to create datasets seems to be ok, however volume creation fails if not superuser

(please note that filesystem creation of descendants  works fine).

### Describe how to reproduce the problem
grant permissions to certain user, then try creating a volume using that user's privileges

### Include any warning/errors/backtraces from the system logs

*IMPORTANT* - Please mark logs and text output from terminal commands 
or else Github will not display them correctly. 
An example is provided below.

Example:
```
sudo zfs allow mibanezm create,destroy,mount,snapshot media1_data
```
this works as expected:
```
zfs create  media1_data/testing     
```
but this fails:
```
zfs create -V 1g media1_data/testing2
cannot create 'media1_data/testing2': permission denied
```

**Comment by ahrens** [comment]
After the `permission denied` message, can you run `zfs list` to see if it was actually created?  I'm wondering if it was actually created, but something went wrong with creating the device links.

**Comment by homerlinux** [comment]
no, volume (testing2) was not created. However, filesystem (testing) was.

**Comment by kpande** [comment]
right, this is a known issue with how Linux works: #4487

**Comment by ahrens** [comment]
https://github.com/zfsonlinux/zfs/pull/4487 is fixed in 0.7.5, which implies that it should support `zfs allow/unallow` in general.  I didn't see anything in that PR explaining why this doesn't work for zvols, but maybe I missed it?  (FWIW, a quick test on master showed the same results.)

**Comment by ahrens** [comment]
@kpande thanks for pointing out that specific comment.  It looks like that's talking about the inability to mount/unmount a filesystem, even though the user is `zfs allow`-ed to create/destroy/mount/unmount it.  I would imagine similar issues for "mounting" zvols, but I don't see an explanation of why the zvol is not allowed to be created.

**Comment by rlaager** [comment]
What is the expected behavior here? (Also, how does this work on Illumos?) If the user creates a volume, and udev populates `/dev` with the device node and `/dev/zvol` with the symlink, the user still can't access the block device.

**Comment by homerlinux** [comment]
>thanks for pointing out that specific comment. It looks like that's talking about the inability to mount/unmount a filesystem, even though the user is zfs allow-ed to create/destroy/mount/unmount it.

Right, the issue here is zvol creation, not mounting. I'm not trying to mount anything.

**Comment by ahrens** [comment]
The issue is that when creating a zvol, by default it also sets a `refreservation`.  You will need to either also allow `refreservation`, or use `zfs create -s -V ...` to create a "sparse" zvol without a refreservation.  This behavior is the same on illumos and linux.  Here's an example on Linux (ZoL master):

```
$ zfs create -V 10M rpool/vol1
cannot create 'rpool/vol1': permission denied
$ sudo zfs allow mahrens create,destroy,mount,snapshot rpool
$ zfs create -V 10M rpool/vol1
cannot create 'rpool/vol1': permission denied
$ zfs create -s -V 10M rpool/vol1
$ zfs list
NAME                              USED  AVAIL     REFER  MOUNTPOINT
rpool                            16.5G  50.8G       64K  none
...
rpool/vol1                         49K  50.8G       49K  -
$ ls -l /dev/zvol/rpool/vol1
lrwxrwxrwx 1 root root 9 Mar 26 16:13 /dev/zvol/rpool/vol1 -> ../../zd0
$ ls -lL /dev/zvol/rpool/vol1
brw-rw---- 1 root disk 230, 0 Mar 26 16:13 /dev/zvol/rpool/vol1
```

It would make sense to update the documentation to make this more clear.  For example, the help message for `zfs allow` could indicate that for `create`, `refreservation` is also required to create a non-sparse zvol (like it mentions `mount`).  There could also be a more verbose explanation in the zfs manpage.

**Comment by rlaager** [comment]
I agree that we can and should update the documentation as described, to address the refreservation issue.

It likely doesn't make any sense to delegate volume `create` to a user that is not in the `disk` group (in the default setup) because they won't be able to access the device anyway, but that's a separate administrative issue outside ZFS's scope.

**Comment by homerlinux** [comment]
@ahrens and rest of the team, thank you for your consideration, now I know how I can workaround my problem. You have been very helpful!
