### ISSUE TITLE
ZFS max write 50MBps on MASTER with dd (bs=default)

### ISSUE THREAD

**Issue by Ornias1993** [zfsonlinux/zfs#9690]
The current MASTER branch does not seem to be able to reach more than around 50MB/s write speed with default DD settings.

This is tested and confirmed on multiple systems with multiple different disks (including RAMDISKS and SSD's) and also confirmed in virtual machine testing.

Even multiple compression algorithms (including "off") are tested.

Note:
System specs vary, but CPU load is not maxed when reaching the 50MB/s ceiling on any of them

### System information
Type | Version/Name
 --- | --- 
Distribution Name	| MIXED (Deb, CENTOS etc)
Distribution Version	|  MIXED
Linux Kernel	| MIXED (4.* )
Architecture	|  x86_64
ZFS Version	|  MASTER
SPL Version	|  MASTER

### Describe the problem you're observing
Using dd to copy a file (compressible or not) onto a zfs dataset, doesn't manage to exceed 50MB/s

### Describe how to reproduce the problem
- dd something onto your dataset
- See low speed

### Include any warning/errors/backtraces from the system logs
Nothing of relevance found.

**Comment by Ornias1993** [comment]
@brainslayer @inicola Please continue the discussion about this here.

**Comment by BrainSlayer** [comment]
as i said before. large pids are normal if your pid_max setting is high. each new process gets a new increased pid. if limit its reached it starts from the beginning

**Comment by BrainSlayer** [comment]
you can control the maximum pids by changing the setting /proc/sys/kernel/pid_max

**Comment by Ornias1993** [comment]
*note* 
Previous comments from @BrainSlayer was a response on the question by @inicola weither he is seeing large PID numbers

**Comment by c0d3z3r0** [comment]
> as i said before. large pids are normal if your pid_max setting is high. each new process gets a new increased pid. if limit its reached it starts from the beginning

ack, I even have pid_max = 4194304

**Comment by BrainSlayer** [comment]
curious. mine is 32768 by default and i configured it to 65536. so who is doing such high pids by default. this is not standard kernel setting

**Comment by Ornias1993** [comment]
> > as i said before. large pids are normal if your pid_max setting is high. each new process gets a new increased pid. if limit its reached it starts from the beginning
> 
> ack, I even have pid_max = 4194304

And it wouldn't explain why it is an issue on master and not on release.

**Comment by lnicola** [comment]
I get 16.2 MB/s on a Samsung 860 EVO both with copies=1 and copies=2 (and no compression), with a slow CPU.

A quick profile seems to indicate high contention:

   5.07%  [kernel]          [k] preempt_count_add
   3.05%  [kernel]          [k] __kmalloc_node
   2.89%  [kernel]          [k] mutex_lock
   2.88%  [kernel]          [k] _raw_spin_lock
   2.45%  [kernel]          [k] mutex_unlock
   2.43%  [kernel]          [k] memset_erms
   2.19%  [kernel]          [k] kfree
   2.10%  [zfs]             [k] zio_create
   1.88%  [kernel]          [k] preempt_count_sub
   1.80%  [zfs]             [k] zfs_write
   1.57%  [zfs]             [k] dsl_dir_tempreserve_space
   1.49%  [zfs]             [k] dbuf_rele_and_unlock
   1.37%  [zfs]             [k] zio_done
   1.37%  [kernel]          [k] in_lock_functions
   1.36%  [zfs]             [k] zio_wait
   1.35%  [kernel]          [k] kmem_cache_alloc
   1.23%  [kernel]          [k] _raw_spin_unlock
   1.22%  [zfs]             [k] dbuf_hold_impl
   1.12%  [zfs]             [k] dmu_buf_hold_array_by_dnode

For the PID thing, see https://github.com/zfsonlinux/zfs/issues/7274. I'm seeing a large number of `z_wr_int` processes them being spawned:

![image](https://user-images.githubusercontent.com/308347/70320572-c40cf580-182d-11ea-9a3d-22098144d91c.png)

I asked because there might be a link between the high contention and the relatively large amount of threads that keep getting started and killed off. I'm running `0.8.0-426_ge69bb31b7`.

**Comment by BrainSlayer** [comment]
i dont see a issue here. this is a OS specific setting. unrelated to zfs and with such a setting you get such insane high pids by the time.

**Comment by c0d3z3r0** [comment]
pids are completely unrelated here

**Comment by BrainSlayer** [comment]
the high amount of threads is also nothing unusual. by default zfs uses 32 threads pre vdev. this setting can be configured at module load time with the parameter zvol_threads. performance wise this setting is way to high. cpu_count * 2 would be better there. but this is only one thread limit setting. there are other threads in zfs in addition, some are limited by cpu count. since i dont have all informations right now in mind, this can be checked. it will definitly have performance impact if the total concurrent running threads are too high. but with running i also mean active. threads can be also in suspended state with no performance impact. this type of thread pooling is not unusual since it does increase performance if a thread doesnt need to be recreated all the time. maybe one of the zfs developers can explain this in more detail since i havent done too much research on this yet

**Comment by Ornias1993** [comment]
@inicola 
I don't think your speed is related to this issue. 
This issue is mostly about a 50MB/s CEILING being observed, not slow speed in general.

Also it might be worthwhile if you are testing with MASTER or release.
Release should be fine (not checked by me though)

**Comment by lnicola** [comment]
> this type of thread pooling is not unusual since it does increase performance if a thread doesnt need to be recreated all the time.

On my system, ZFS started and stopped about 420 000 threads in 18 hours. That's something that a thread pool would have avoided if it was used.

> Also it might be worthwhile if you are testing with MASTER or release.

I'm running `e69bb31b71f60b338fa5510dc48de298f394ad73`, but I've noticed this two weeks ago.

> Even with the observed bug, compression=off should hit the ceiling of 50MB/s that is being observed

My CPU is very slow (a Celeron).

**Comment by Ornias1993** [comment]
@inicola What celeron?
It might be that this ceiling is CPU related

@BrainSlayer What CPU did you use while doing my requested speed test?

@dan-and What CPU did you use while doing the speed test?

However, My cpu is far from being saturated while doing it.... so it's not saturation thats the issue here.

**Comment by lnicola** [comment]
> What celeron?

It's a Celeron [J1900](https://ark.intel.com/content/www/us/en/ark/products/78867/intel-celeron-processor-j1900-2m-cache-up-to-2-42-ghz.html) from 2013.

> However, My cpu is far from being saturated while doing it.... so it's not saturation thats the issue here.

Well...

![image](https://user-images.githubusercontent.com/308347/70321304-a771bd00-182f-11ea-95e8-37a327395ed3.png)

**Comment by lnicola** [comment]
I guess we should test with larger reads :-).

```
$ dd bs=1M if=test.mkv of=test2.mkv status=progress conv=fdatasync
1320157184 bytes (1.3 GB, 1.2 GiB) copied, 6 s, 220 MB/s
1260+1 records in
1260+1 records out
1321623113 bytes (1.3 GB, 1.2 GiB) copied, 12.215 s, 108 MB/s
```

**Comment by Ornias1993** [comment]
I tested it with a 1GB file:

**Comment by Ornias1993** [comment]
So it's an issue with blocksize inefficiency? Let me test that be back in 15.

**Comment by Ornias1993** [comment]
If bs is the issue, this is really an ZFS quirck that should be documented:
https://serverfault.com/questions/650086/does-the-bs-option-in-dd-really-improve-the-speed

**Comment by c0d3z3r0** [comment]
> If bs is the issue, this is really an ZFS quirck that should be documented:

not sure if it is a ZFS issue then. AFAIK dd tries to select a proper bs but I don't know how

**Comment by Ornias1993** [comment]
Okey guys I got the metrics...
Yes bs setting is the culprid. BS=1M solved this issue.

However, this is not normal dd behavior...

**Comment by c0d3z3r0** [comment]
> However, this is not normal dd behavior...

what do you mean?

**Comment by Ornias1993** [comment]
I closed it as it isn't truely relevant as an issue anymore. We can reopen if we are sure ZFS is the culprid.

@c0d3z3r0 
If I do the same to a drive without ZFS, It works perfectly fine.

**Comment by c0d3z3r0** [comment]
> @c0d3z3r0
> If I do the same to a drive without ZFS, It works perfectly fine.

hm, could depend on the physical bs. when I use dd, I always add bs=1M or bs=2M

**Comment by Ornias1993** [comment]
4 different drives (IMG on ramdisk, Virtual drive on ramdisk, SSD, HDD)
All have the same issue... and only while running it through zfs....

**Comment by Ornias1993** [comment]
Both BS=1M and BS=4M work fine. BS=4M gives slightly beter performance.
Running BS=2M now.

**Comment by c0d3z3r0** [comment]
did you try different values for shift?

**Comment by Ornias1993** [comment]
Working theory:
Maybe ZFS acts like the blocks from dd are seperate files?
That would explain the performance drop...

**Comment by Ornias1993** [comment]
@c0d3z3r0 Yes, actually I trashed the first try because it was accidentally ashift=9 xD

**Comment by c0d3z3r0** [comment]
> @c0d3z3r0 Yes, actually I trashed the first try because it was accidentally ashift=9 xD

\o/ any differences between 11, 12, 13?

**Comment by Ornias1993** [comment]
@c0d3z3r0 Not tested.

**Comment by c0d3z3r0** [comment]
> @c0d3z3r0 Not tested.

that could have an influence

**Comment by Ornias1993** [comment]
An influence: yes. 
But this influence is too big.

We are talking 50MB/s where there should be almost 900MB/s on that zfsdataset.

**Comment by Ornias1993** [comment]
I think my working theory would describe the symphoms best.

**Comment by Ornias1993** [comment]
Trying to write many 512 size files a second, would explain a HUGE performance drop.

**Comment by Ornias1993** [comment]
bs=4M seems to be the sweet spot, but the difference with 2M is minimal.
This minimal difference might actually be explained by ashift @c0d3z3r0 ;) 
Like talking 20-40MB/s difference (770vs790 for example) is explainable that way.

**Comment by Ornias1993** [comment]
Thanks @inicola 
This at least solved my problem and I can now finally finish my automated compression test script:
https://github.com/Ornias1993/zfs-compression-test

**Comment by lnicola** [comment]
Every file system will have some IO overhead. With ZFS, that overhead seems to be somewhat large, so these 512 bytes reads bring my CPU to its knees. That's not to say it couldn't be faster, but it's not surprising. In this case, ZFS recommends an IO size of 128 KB.

```
$ echo 3 | sudo tee /proc/sys/vm/drop_caches           
3
$ dd if=test.mkv of=/dev/null status=progress bs=128k
727711744 bytes (728 MB, 694 MiB) copied, 2 s, 364 MB/s
10083+1 records in
10083+1 records out
1321623113 bytes (1.3 GB, 1.2 GiB) copied, 2.92039 s, 453 MB/s
$ dd if=test.mkv of=/dev/null status=progress bs=128k # warm cache
1318322176 bytes (1.3 GB, 1.2 GiB) copied, 1 s, 1.3 GB/s
10083+1 records in
10083+1 records out
1321623113 bytes (1.3 GB, 1.2 GiB) copied, 1.00277 s, 1.3 GB/s
$ dd if=test.mkv of=/dev/null status=progress bs=512 # still warm cache
1296782848 bytes (1.3 GB, 1.2 GiB) copied, 22 s, 58.9 MB/s 
2581295+1 records in
2581295+1 records out
1321623113 bytes (1.3 GB, 1.2 GiB) copied, 22.4206 s, 58.9 MB/s
```

**Comment by Ornias1993** [comment]
@inicola yes, I think every BS in DD is a seperate IO order.
In your case that takes down your CPU, in my case ZFS itself is bottlenecking IO for some reason.

**Comment by BrainSlayer** [comment]
@Ornias1993 i already wrote you my cpu spec at the other PR, where you initially requested it 
model name      : Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

**Comment by Ornias1993** [comment]
@BrainSlayer As I berated  you about in the other thread, this issue has been solved.
It has been concluded that its just a quirk with ZFS + default DD BS size.

Thanks for sharing anyway.

**Comment by BrainSlayer** [comment]
so 128k. blocksize is worth of doing a new test. okay

**Comment by BrainSlayer** [comment]
for compression. not much difference
dd if=GPL_RT-AX88U_3.0.0.4.384.4736-g47a9d71.tar of=/mnt/zfs/test.tar status=progress bs=128k
4017750016 bytes (4.0 GB, 3.7 GiB) copied, 55 s, 72.8 MB/s
33803+1 records in
33803+1 records out

**Comment by BrainSlayer** [comment]
decompression.
linux:/xfs/asus # echo 3 > /proc/sys/vm/drop_caches
linux:/xfs/asus # dd of=/dev/null if=/mnt/zfs/test.tar status=progress bs=128k
3869245440 bytes (3.9 GB, 3.6 GiB) copied, 26 s, 149 MB/s

**Comment by BrainSlayer** [comment]
alternate block size
linux:/xfs/asus # dd of=/dev/null if=/mnt/zfs/test.tar status=progress bs=4M
3741319168 bytes (3.7 GB, 3.5 GiB) copied, 12 s, 312 MB/s

**Comment by BrainSlayer** [comment]
no block size set
linux:/xfs/asus # dd of=/dev/null if=/mnt/zfs/test.tar status=progress
4403455488 bytes (4.4 GB, 4.1 GiB) copied, 17 s, 259 MB/s

**Comment by Ornias1993** [comment]
What distro are you running?
Maybe different distro's set a different default BS?

**Comment by BrainSlayer** [comment]
@Ornias1993 opensuse leap 15.1. but default bs is not given by os. its dd default. by default dd uses 512 bytes

**Comment by Ornias1993** [comment]
@BrainSlayer This issue has been solved. I'll leave it at that.
TL:DR
Use BS=4M with zfs.

**Comment by BrainSlayer** [comment]
i tested  BS=4M already. it has no significant impact, except for reducing io load. 

with zstd
linux:/xfs/asus # dd if=GPL_RT-AX88U_3.0.0.4.384.4736-g47a9d71.tar of=/mnt/zfs/test333.tar status=progress bs=4M

4072669184 bytes (4.1 GB, 3.8 GiB) copied, 69 s, 59.0 MB/s
1056+1 records in
1056+1 records out
4430673920 bytes (4.4 GB, 4.1 GiB) copied, 69.4666 s, 63.8 MB/s

without compression
linux:/xfs/asus # dd if=GPL_RT-AX88U_3.0.0.4.384.4736-g47a9d71.tar of=/mnt/zfs/test334.tar status=progress bs=4M
3783262208 bytes (3.8 GB, 3.5 GiB) copied, 70 s, 53.9 MB/s
1056+1 records in
1056+1 records out
4430673920 bytes (4.4 GB, 4.1 GiB) copied, 70.3975 s, 62.9 MB/s

**Comment by Ornias1993** [comment]
@BrainSlayer It does solve my issue completely.
Using BS=4M my test script works and is conformed working by others.

I'm not interested in this discussion any longer.

**Comment by BrainSlayer** [comment]
so. bug persists, you are just not interested in it. case closed.

**Comment by BrainSlayer** [comment]
and there is no proof that it works for others. the tests above by the other guy is just decompression / reading test. but its no write test.

**Comment by lnicola** [comment]
```
# zfs create -o compression=off -o copies=1 smart/srv/foo
# cd /srv/foo                                                 

# sudo dd if=/tank/download/test.mkv of=test2.mkv status=progress bs=2M
1287651328 bytes (1.3 GB, 1.2 GiB) copied, 9 s, 143 MB/s
630+1 records in
630+1 records out
1321623113 bytes (1.3 GB, 1.2 GiB) copied, 9.23995 s, 143 MB/s

# sudo dd if=/tank/download/test.mkv of=test2.mkv status=progress bs=2M
1195376640 bytes (1.2 GB, 1.1 GiB) copied, 7 s, 171 MB/s
630+1 records in
630+1 records out
1321623113 bytes (1.3 GB, 1.2 GiB) copied, 7.73925 s, 171 MB/s

# sudo dd if=/tank/download/test.mkv of=test2.mkv status=progress bs=512
396221440 bytes (396 MB, 378 MiB) copied, 25 s, 15.8 MB/s^C
775806+0 records in
775806+0 records out
397212672 bytes (397 MB, 379 MiB) copied, 25.062 s, 15.8 MB/s

# zfs set compression=on smart/srv/foo                                  
# sudo dd if=/tank/download/test.mkv of=test2.mkv status=progress bs=2M 
1314914304 bytes (1.3 GB, 1.2 GiB) copied, 5 s, 263 MB/s 
630+1 records in
630+1 records out
1321623113 bytes (1.3 GB, 1.2 GiB) copied, 5.0234 s, 263 MB/s
```

170 MB/s does seem a bit on the low side. It does get faster in follow-up runs, but I can't make it go past 280 MB/s (without compression).

**Comment by BrainSlayer** [comment]
if i test using a 1 gb file its very fast for me too. the problem is that the cache eats it. that why i use a 4 gb file for testing which flushes already at 1 gb in my tests

**Comment by lnicola** [comment]
```
# zfs set compression=off smart/srv/foo                                

# dd if=/tank/download/another_file.mkv of=test2.mkv status=progress bs=2M 
14262730752 bytes (14 GB, 13 GiB) copied, 98 s, 146 MB/s^C
6816+0 records in
6815+0 records out
14292090880 bytes (14 GB, 13 GiB) copied, 98.2787 s, 145 MB/s

# zfs set compression=on smart/srv/foo                                                                                     
# echo 3 | tee /proc/sys/vm/drop_caches            
3

# dd if=/tank/download/another_file.mkv of=test2.mkv status=progress bs=2M 
11941183488 bytes (12 GB, 11 GiB) copied, 76 s, 157 MB/s^C
5729+0 records in
5728+0 records out
12012486656 bytes (12 GB, 11 GiB) copied, 76.5279 s, 157 MB/s
```

**Comment by BrainSlayer** [comment]
at least faster than on my system. but not fast. but its a standard hdd, its okay

**Comment by lnicola** [comment]
It's reading from a HDD (or cache in the earlier test) and writing to an SSD. I feel it should be faster, but my CPU is not great:

![image](https://user-images.githubusercontent.com/308347/70389911-6532b200-19ce-11ea-9b84-a3f8549e7d42.png)
